import { ImageObject } from './image-object';

export const ContentData: ImageObject[] = [
  { id: 1, name: 'Jeans with Belt', category: 'trend', path: '../assets/belt-jeans.jpg' },
  { id: 2, name: 'Blazer', category: 'trend', path: '../assets/blazer.jpg' },
  { id: 3, name: 'Blouses on Rail', category: 'shop', path: '../assets/blouses-on-rail.jpg' },
  { id: 4, name: 'Blue Shoe', category: 'trend', path: '../assets/blue-shoe.jpg' },
  { id: 5, name: 'Blue Suit Tie', category: 'trend', path: '../assets/blue-suit-tie.jpg' },
  { id: 6, name: 'Carnival', category: 'explore', path: '../assets/carnival.jpg' },
  { id: 7, name: 'Colorful Cotton', category: 'shop', path: '../assets/colourful-cotton.jpg' },
  { id: 8, name: 'Colorful Jacket', category: 'explore', path: '../assets/colourful-jacket.jpg' },
  { id: 9, name: 'Curley Hair', category: 'trend', path: '../assets/curley-hair.jpg' },
  { id: 10, name: 'Denim Jacket', category: 'trend', path: '../assets/.jpg' },
  { id: 11, name: 'Disco Hat', category: 'explore', path: '../assets/disco-hat.jpg' },
  { id: 12, name: 'Egyptian Robe', category: 'explore', path: '../assets/egyptian.jpg' },
  { id: 13, name: 'Fashion Set', category: 'shop', path: '../assets/fashion-set-01.jpg' },
  { id: 14, name: 'Fashion Set', category: 'shop', path: '../assets/fashion-set-02.jpg' },
  { id: 15, name: 'Fur Jacket', category: 'trend', path: '../assets/fur-jacket.jpg' },
  { id: 16, name: 'Grey Jacket Tie', category: 'trend', path: '../assets/grey-jacket-tie.jpg' },
  { id: 17, name: 'Hat', category: 'trend', path: '../assets/.png' },
  { id: 18, name: 'Jeans Zipper', category: 'shop', path: '../assets/jeans-zipper.jpg' },
  { id: 19, name: 'Jeans', category: 'shop', path: '../assets/jeans.jpg' },
  { id: 20, name: 'Jumper Rail', category: 'shop', path: '../assets/jumper-rail.jpg' },
  { id: 21, name: 'Pink Hair', category: 'explore', path: '../assets/pink-hair.jpg' },
  { id: 22, name: 'Pocket Watch', category: 'explore', path: '../assets/pocket-watch-02.jpg' },
  { id: 23, name: 'Pocket Watch', category: 'explore', path: '../assets/red-hair.jpg' },
  { id: 24, name: 'Rolex', category: 'shop', path: '../assets/rolex.jpg' },
  { id: 25, name: 'Round Glasses', category: 'trend', path: '../assets/round-glasses.jpg' },
  { id: 26, name: 'Scarf Railing', category: 'shop', path: '../assets/scarf-railing.jpg' },
  { id: 27, name: 'Shirt Railing', category: 'shop', path: '../assets/shirt-railing.jpg' },
  { id: 28, name: 'Shirt-sleeves', category: 'shop', path: '../assets/shirt-sleeves.jpg' },
  { id: 29, name: 'Shirt Bow', category: 'shop', path: '../assets/shirts-bow.jpg' },
  { id: 30, name: 'Boot', category: 'explore', path: '../assets/shoes-boot.jpg' },
  { id: 31, name: 'Silk Ties', category: 'shop', path: '../assets/silk-tie-shop.jpg' },
  { id: 32, name: 'Skirts', category: 'explore', path: '../assets/skirts.jpg' },
  { id: 33, name: 'Shades', category: 'trend', path: '../assets/smiling-sunglasses.jpg' },
  { id: 34, name: 'Store', category: 'shop', path: '../assets/store-clothes.jpg' },
  { id: 35, name: 'Hat', category: 'explore', path: '../assets/strohute.jpg' },
  { id: 36, name: 'Denim Shirt', category: 'explore', path: '../assets/stylish-boy-woods.jpg' },
  { id: 37, name: 'Suits on Rail', category: 'shop', path: '../assets/suits.jpg' },
  { id: 38, name: 'Sunglasses', category: 'explore', path: '../assets/sunglasses-focus.jpg' },
  { id: 39, name: 'Pink Bow', category: 'explore', path: '../assets/tie-pink.jpg' },
  { id: 40, name: 'Red Tie', category: 'explore', path: '../assets/tie-tailor.jpg' },
  { id: 41, name: 'Tops Shorts', category: 'trend', path: '../assets/tops-shorts.jpg' },
  { id: 42, name: 'T-shirt Shop', category: 'shop', path: '../assets/tshirt-shop.jpg' },
  { id: 43, name: 'Drindl', category: 'explore', path: '../assets/turkish.jpg' },
  { id: 44, name: 'Wedding Dresses', category: 'explore', path: '../assets/wedding-dresses.jpg' },
  { id: 45, name: 'White Fork', category: 'explore', path: '../assets/white-fork.jpg' },
  { id: 46, name: 'Red Shoes', category: 'explore', path: '../assets/womens-shoes-red.jpg' },
  { id: 47, name: 'Stripes', category: 'explore', path: '../assets/wppd-dress.jpg' },
  { id: 48, name: 'Sunglasses', category: 'shop', path: '../assets/wood-sunglasses.jpg' },
  { id: 49, name: 'Wool Balls', category: 'shop', path: '../assets/wool-balls.jpg' }
]
