import { ImageObject } from './app/section/main/image-object';

export const ContentData: ImageObject[] = [
  { id: 1, name: 'Carnival', category: 'explore',
    tag: 'carnival costume forehead hat jewellery', path: './assets/carnival.jpg' },
  { id: 2, name: 'Jeans', category: 'shop',
    tag: 'blue denim cooper jeans lee stack', path: './assets/jeans.jpg' },
  { id: 3, name: 'Fashion Set', category: 'shop',
    tag: 'bag belt boots camera hiker leather pouch scarf stripe sunglasses t-shirt', path: './assets/fashion-set-01.jpg' },
  { id: 4, name: 'Blouses on Rail', category: 'shop',
    tag: 'blouses grey light rail trousers', path: './assets/blouses-on-rail.jpg' },
  { id: 5, name: 'Blue Suit Tie', category: 'trend',
    tag: 'blue navy pocket square suit tie', path: './assets/blue-suit-tie.jpg' },
  { id: 6, name: 'Jeans with Belt', category: 'trend',
    tag: 'belt blue denim jeans leather', path: './assets/belt-jeans.jpg' },
  { id: 7, name: 'Colorful Cotton', category: 'shop',
    tag: 'color colour cotton rack thread', path: './assets/colourful-cotton.jpg' },
  { id: 8, name: 'Colorful Jacket', category: 'explore',
    tag: 'colorful colourful jacket red shorts', path: './assets/colourful-jacket.jpg' },
  { id: 9, name: 'Nail Polish', category: 'trend',
    tag: 'brown gloves nail polish', path: './assets/nail-polish-coffee.jpeg' },
  { id: 10, name: 'Denim Jacket', category: 'trend',
    tag: 'blue denim jacket sky tops white', path: './assets/denim-jacket.jpg' },
  { id: 11, name: 'Kimono', category: 'explore',
    tag: 'japanese kimono', path: './assets/kimono.jpeg' },
  { id: 12, name: 'Egyptian Robe', category: 'explore',
    tag: 'brown egyptian robe', path: './assets/egyptian.jpg' },
  { id: 13, name: 'Blazer', category: 'trend',
    tag: 'blazer tweed', path: './assets/blazer.jpg' },
  { id: 14, name: 'Fashion Set', category: 'shop',
    tag: 'charcoal leather red scarf shoes suit tie', path: './assets/fashion-set-02.jpg' },
  { id: 15, name: 'Fur Jacket', category: 'trend',
    tag: 'fur grey jacket', path: './assets/fur-jacket.jpg' },
  { id: 16, name: 'Grey Jacket Tie', category: 'trend',
    tag: 'grey polkadots suit tie', path: './assets/grey-jacket-tie.jpg' },
  { id: 17, name: 'Hat', category: 'trend',
    tag: 'beige hat straw', path: './assets/hat.png' },
  { id: 18, name: 'Jeans Zipper', category: 'shop',
    tag: 'denim jeans zipper', path: './assets/jeans-zipper.jpg' },
  { id: 19, name: 'Blue Shoe', category: 'trend',
    tag: 'blue heels shoes', path: './assets/blue-shoe.jpg' },
  { id: 20, name: 'Jumper Rail', category: 'shop',
    tag: 'cardigan jumper rail brown', path: './assets/jumpers-rail.jpg' },
  { id: 21, name: 'Pink Hair', category: 'explore',
    tag: 'hair hot pink', path: './assets/pink-hair.jpg' },
  { id: 22, name: 'Pocket Watch', category: 'explore',
    tag: 'black pocket watch', path: './assets/pocket-watch-02.jpg' },
  { id: 23, name: 'Pocket Watch', category: 'explore',
    tag: 'golden pocket watch', path: './assets/pocket-watch.jpg' },
  { id: 24, name: 'Rolex', category: 'shop',
    tag: 'aqua rolex silver', path: './assets/rolex.jpg' },
  { id: 25, name: 'Round Glasses', category: 'trend',
    tag: 'jacket leather round sunglasses', path: './assets/round-glasses.jpg' },
  { id: 26, name: 'Scarf Railing', category: 'shop',
    tag: 'rail scarf', path: './assets/scarf-railing.jpg' },
  { id: 27, name: 'Shirt Railing', category: 'shop',
    tag: 'rail shirts', path: './assets/shirt-railing.jpg' },
  { id: 28, name: 'Shirt-sleeves', category: 'shop',
    tag: 'rail shirts', path: './assets/shirt-sleeves.jpg' },
  { id: 29, name: 'Shirt Bow', category: 'shop',
    tag: 'bows shirts', path: './assets/shirts-bow.jpg' },
  { id: 30, name: 'Boot', category: 'explore',
    tag: 'beanie fur boots', path: './assets/shoes-boot.jpg' },
  { id: 31, name: 'Silk Ties', category: 'shop',
    tag: 'ties', path: './assets/silk-tie-shop.jpg' },
  { id: 32, name: 'Skirts', category: 'explore',
    tag: 'flowry sandals skirts', path: './assets/skirts.jpg' },
  { id: 33, name: 'Shades', category: 'trend',
    tag: 'clubmaster sunglasses', path: './assets/smiling-sunglasses.jpg' },
  { id: 34, name: 'Store', category: 'shop',
    tag: 'men\'s shop', path: './assets/store-clothes.jpg' },
  { id: 35, name: 'Hat', category: 'explore',
    tag: 'beige hats straw', path: './assets/strohute.jpg' },
  { id: 36, name: 'Denim Shirt', category: 'trend',
    tag: 'denim jeans shirt sunglasses', path: './assets/stylish-boy-woods.jpg' },
  { id: 37, name: 'Suits on Rail', category: 'shop',
    tag: 'rail suits', path: './assets/suits.jpeg' },
  { id: 38, name: 'Sunglasses', category: 'explore',
    tag: 'round sunglasses', path: './assets/sunglasses-focus.jpg' },
  { id: 39, name: 'Pink Bow', category: 'explore',
    tag: 'bow pink', path: './assets/tie-pink.jpg' },
  { id: 40, name: 'Red Tie', category: 'explore',
    tag: 'red tie', path: './assets/tie-tailor.jpg' },
  { id: 41, name: 'Tops Shorts', category: 'trend',
    tag: 'shorts tops', path: './assets/tops-shorts.jpg' },
  { id: 42, name: 'T-shirt Shop', category: 'shop',
    tag: 'jumper knit shop', path: './assets/tshirt-shop.jpg' },
  { id: 43, name: 'Drindl', category: 'explore',
    tag: 'drindl green', path: './assets/turkish.jpg' },
  { id: 44, name: 'Wedding Dresses', category: 'explore',
    tag: 'dress shop wedding white', path: './assets/wedding-dresses.jpg' },
  { id: 45, name: 'White Fork', category: 'explore',
    tag: 'dress white', path: './assets/white-frok.jpg' },
  { id: 46, name: 'Red Shoes', category: 'trend',
    tag: 'heels red shoes', path: './assets/womens-shoes-red.jpg' },
  { id: 47, name: 'Stripes', category: 'explore',
    tag: 'hat stripes', path: './assets/wood-dress.jpg' },
  { id: 48, name: 'Sunglasses', category: 'shop',
    tag: 'sunglasses square', path: './assets/wood-sunglasses.jpg' },
  { id: 49, name: 'Wool Balls', category: 'shop',
    tag: 'balls wool', path: './assets/wool-balls.jpg' },
  { id: 50, name: 'Accesories Shop', category: 'shop',
    tag: 'bags leather', path: './assets/bright-shop.jpeg' },
  { id: 51, name: 'Converse Shades', category: 'trend',
    tag: 'converse sunglasses white', path: './assets/converse-shades.jpg' },
  { id: 52, name: 'Converse', category: 'trend',
    tag: 'converse', path: './assets/converse.jpg' },
  { id: 53, name: 'Dark Tattoo', category: 'explore',
    tag: 'tattoo', path: './assets/dark-tattoo.jpeg' },
  { id: 54, name: 'Demin Fabric', category: 'explore',
    tag: 'blue denim jeans', path: './assets/denim-fabric.jpg' },
  { id: 55, name: 'Green Saree', category: 'explore',
    tag: 'green indian saree', path: './assets/indian-saree.jpeg' },
  { id: 56, name: 'Jeans Button', category: 'trend',
    tag: 'denim jeans', path: './assets/jeans-button.jpg' },
  { id: 57, name: 'Disco Hat', category: 'explore',
    tag: 'black hat', path: './assets/disco-hat.png' },
  { id: 58, name: 'Business Shoe', category: 'trend',
    tag: 'leather shoes wine', path: './assets/leather-shoes-toe.jpg' },
  { id: 59, name: 'Makeup palette', category: 'shop',
    tag: 'brush makeup', path: './assets/makeup-palette.jpeg' },
  { id: 60, name: 'Man in Black', category: 'trend',
    tag: 'black hat jumper', path: './assets/man-in-black.jpeg' },
  { id: 61, name: 'Masai tribe', category: 'explore',
    tag: 'african masai red', path: './assets/masai-people.jpeg' },
  { id: 62, name: 'Curley Hair', category: 'trend',
    tag: 'curley hair', path: './assets/curley-hair.jpg' },
  { id: 63, name: 'Nail Polish', category: 'shop',
    tag: 'nail polish', path: './assets/nail-polishes.jpeg' },
  { id: 64, name: 'Heels and Bag', category: 'shop',
    tag: 'bag heels red shoes', path: './assets/shop-shelf.jpeg' },
  { id: 65, name: 'Shopaholic', category: 'shop',
    tag: 'shopping shopaholic', path: './assets/shopaholic.jpeg' },
  { id: 66, name: 'Trainers', category: 'trend',
    tag: 'black green trainers', path: './assets/sports-shoes.jpg' },
  { id: 49, name: 'Red Hijab', category: 'explore',
    tag: 'arab red hijab', path: './assets/red-hijab.jpg' }
]
